= Guia prático de instalação do Service Mesh 3 no Openshift 4
Rodrigo Ramalho
:toc:
:toclevels: 3
:sectnums:

== Introdução

Instalação e configuração do Service Mesh 3 no OpenShift 4, utilizando o modelo de RBAC por persona para garantir segurança e aderência ao princípio de privilégio mínimo. Este guia é voltado para administradores de cluster e operadores que desejam implementar o Service Mesh em seus ambientes OpenShift.

== Pre Requirements 

. OpenShift Service Mesh Operator
. Kiali Operator provided by Red Hat
. OpenTelemetry Operator
. Tempo Operator / plataforma de distributed tracing (Tempo)
. Openshift Monitoring Working properly
. User-workload monitoring enabled

== Create namespace Resource e Quotas 
```
oc create -f namespace/namespace.yml
## Only as an example in case you need to set quotas and limits for the namespace.
# oc create -f namespace/resource-quota.yml 
# oc create -f namespace/limit-range.yml
```

== Deploy test application 

```
oc new-app nodejs~https://github.com/sclorg/nodejs-ex.git
```

== Egress IP 

. Deploy nodeJS application. 
. Inside the `Terminal` in the NodeJS application run: 
```
curl -4 https://api.ipify.org
```

. Get the IP. 
. Check if the nodes has the label `egress-assignable`
```
oc get nodes -L k8s.ovn.org/egress-assignable
```

. If yes, let's create the egressip route. Change the IP for a IP that is valid for your network

```
oc create -f ingress-egress/route-egressip.yml
```

. Useful commands 
```
# List nodes
oc get nodes -o wide
# Check if node is available
oc get node worker-cluster-2n6cl-3 -o json | jq '.metadata.labels | has("k8s.ovn.org/egress-assignable")'
```

. Check if `OVNKubernetes ` is in use.
```
oc get network.config.openshift.io cluster -o jsonpath='{.status.networkType}{"\n"}'
```