apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-deployer-binding
  namespace: app-x-dev
subjects:
- kind: ServiceAccount
  name: pipeline-sa
  namespace: app-x-dev
roleRef:
  kind: Role
  name: pipeline-deployer
  apiGroup: rbac.authorization.k8s.io
