apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operators-edit
  namespace: app-x-hml
subjects:
- kind: Group
  name: team-a-operators
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
